stages:
  - golang
  - deploy

cache:
  key: edu_system
  paths:
    - "$CI_PROJECT_DIR/.cache"

job_golang:
  stage: golang
  image: golang:alpine
  tags:
    - edu-back-end
  script:
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - go env -w GOPROXY=https://proxy.golang.com.cn,direct
    - go get
    - go test ./test
    - go build -o app
    - chmod +x app
  artifacts:
    paths:
      - ./app
    expire_in: 1 week

job_deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  tags:
    - edu-front-end
  script:
    - ls
    - echo "正在生成索引缓存索引提供搜索安装速度"
    - echo "下载所需工具"
    - sh ./cmd/download.sh
    - echo "加载环境变量"
    - export SSHPASS="$PASSWORD"
    - bash ./cmd/go_build.sh
    - bash ./cmd/cache.sh
    - echo "任务完成"
    - ls
    - pwd
    - rm -rf *
